option print_precision 6;
#option log_file ("data_time" & m & ".txt");
option log_file ("data_time1_horseshoe2.txt");

print max{i in V, p in P0} temp[i,p];
print number_of_steps;
print card(W)+number_of_odd_nodes/2-1;
print {v in V} X[v];
print {v in V} Y[v];
print {(i,ti,j,tj) in WW_Exp: x[i,ti,j,tj]>0.5}: i,ti,j,tj,0;
print {(i,j,tj) in A_Exp: y[i,j,tj]>0.5}: i,tj,j,tj,1;
for {p in P0}{ print {i in V} temp[i,p];}


option log_file "";
close;